steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --tag
      - gcr.io/$PROJECT_ID/dockernodejs:$COMMIT_SHA
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/dockernodejs:$COMMIT_SHA
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - dockernodejs
      - --image
      - gcr.io/$PROJECT_ID/dockernodejs:$COMMIT_SHA
      - --region
      - us-central1
      - --platform
      - managed
images:
  - gcr.io/$PROJECT_ID/dockernodejs:$COMMIT_SHA

